#!/usr/bin/expect

spawn sudo su postgres

expect "postgres@localhost's password: "
send "Pa\$\$w0rd\n"

expect "$ "
send "psql -U postgres edca < owner_dashboard.sql\n"

expect "$ "
send "psql -U postgres -c \"set search_path to dashboard;\"\n"

expect "dashboard=# "
send "psql edca\n"

expect "edca=# "
send "\\d\n"

expect "edca=# "
send "\\q\n"

expect "$ "
send "exit\n"

send "Script owner_dashboard.sql ejecutado!"

expect eof
